### ISSUE TITLE
Warnings after homebridge 1.3.1 upgrade

### ISSUE THREAD

**Issue by vzlgdu** [arachnetech/homebridge-mqttthing#414]
After ugraded to homebrdge 1.3.1, I'm receiving the following messages:

[homebridge-mqttthing] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.

**Comment by kremik** [comment]
The same here. Tons of invalid values:

`[homebridge-mqttthing] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 5. See https://git.io/JtMGR for more info.`

`[2/27/2021, 9:49:44 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 5. See https://git.io/JtMGR for more info.`

`[2/27/2021, 9:45:38 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Carbon Monoxide Level': characteristic was supplied illegal value: number 138 exceeded maximum of 100. See https://git.io/JtMGR for more info.`

`[2/27/2021, 9:44:24 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.`

**Comment by Shaky50** [comment]
Same here with HB 1.3.2
Did set HB to debug mode (as instructed) so I guess just need to wait now...

**Comment by arachnetech** [comment]
I've just updated and I can reproduce this by publishing 'bad' values from MQTT. From the page linked to in the warning message (https://git.io/JtMGR), Homebridge is now checking for incorrect values and logging warnings. I don't know whether it also stops them from from being passed on to Homekit (where it seems they can cause 'not responding' issues). If it does stop them, the warnings can probably safely be ignored. If not, MQTTThing should really  be modified to perform its own validation and stop invalid values itself.

I will try to find out more. If MQTTThing does need to be modified to perform its own validation, this may take some time to add.

**Comment by Shaky50** [comment]
Thanks you David for the prompt reply.
You guys are very efficient and professional.

To avoid all the warnings and potential issues/problems between HB & HK I simply rolled-back to my previous version of HB (1.1.7) and it’s back to normal.

This is a great plug-in by the way and I’m just starting to discover it’s potential.

Thank you again and best regards,
Henri
---/a

**Comment by arachnetech** [comment]
I've implemented something which should fix this, but I haven't had a chance to test it fully. 

Consequently I've published it as a beta version for now: 1.1.26-beta.0.

**Comment by EfficientSetting** [comment]
I'm on 1.1.27 and have lots of these warnings all over the console. Did your change make it into the 1.1.27 or did it stay with the beta?

**Comment by arachnetech** [comment]
Validation is in 1.1.27, but I missed a few types which results in lots of warnings. Attempting to fix now...

Sorry I've been so slow to fix this.

**Comment by arachnetech** [comment]
Validation should be working better in 1.1.28.

**Comment by EfficientSetting** [comment]
> Validation is in 1.1.27, but I missed a few types which results in lots of warnings. Attempting to fix now...
> 
> Sorry I've been so slow to fix this.

We are always grateful for your amazing work! 

1.1.28 fixes all the warnings I was seeing before and I'm down to warnings that are due to my own doing now.

Thanks!

**Comment by arachnetech** [comment]
Excellent! Thanks for confirming.

**Comment by mhuca** [comment]
I'm on Homebridge Mqttthing homebridge-mqttthing v1.1.28

but still getting this warning... is there anything I can do to track down where the problem is... 

5/28/2021, 9:42:16 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:42:35 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:43:05 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:43:42 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:44:05 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:44:14 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:44:37 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:44:51 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:45:07 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:47:44 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:47:59 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:48:28 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:48:43 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:53:52 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[5/28/2021, 9:54:13 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[

**Comment by jat80** [comment]
> I'm on Homebridge Mqttthing homebridge-mqttthing v1.1.28
> 
> but still getting this warning... is there anything I can do to track down where the problem is...
> 
> 5/28/2021, 9:42:16 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:42:35 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:43:05 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:43:42 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:44:05 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:44:14 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:44:37 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:44:51 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:45:07 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:47:44 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:47:59 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:48:28 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:48:43 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:53:52 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [5/28/2021, 9:54:13 PM] [homebridge-mqttthing] This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info. [

I'm also getting this still.  Is it something to worry about?

This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

**Comment by jat80** [comment]
This is still an issue

**Comment by superbraz** [comment]
no help?
